name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit changes if there are any
      run: |
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "generated"

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${GH_PAT}@github.com/shuvo8220/shuvo8220.git
